accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # path('successCallback/', views.successCallback, name='successCallback'),
    # path('failureCallback/', views.failureCallback, name='failureCallback'),
    # path('oauth2callback/')
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    # path('oauth2callback/', views.oAuth2CallBackView, name="oauth2callback"),
    # path('recover/', views.pass_recovery, name='recover'),
    # path('logout', views.logout, name="logout"),
    # path('recover/sent', views.sent_link, name='sent-link'),
    # path("reset", views.reset_password, name="reset-password"),
    path('signout/', views.signout, name='signout')
]

homepage/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name="about"),
    path('contact_us/', views.contact_us, name="contact"),
    path('faq/', views.faq, name="faq"),
    path('recover_password/',views.recover_password, name="recover_password"),
    path('reset_link/',views.reset_link, name="reset_link"),
    path('reset_password/',views.reset_password, name="reset_password"),
    path('blog/',views.blog_list, name="blog"),
    path('blog/post/',views.blog_post, name="blog_post"),
    path('blog/search/',views.blog_search, name="blog_search")
]

microapi_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homepage.urls")),
    # path('blog/', include('blog')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('dashboard/', include('user_dashboard.urls', namespace="dashboard")),
    path('', include("api_docs.urls")),
    path('accounts/', include('allauth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_dashboard/urls.py
from django.urls import path, re_path
from . import views

app_name = "user_dashboard"

urlpatterns = [
    path("main/", views.dash, name="dash_main"),
    path("main/<str:name>", views.oneproj, name="dash_proj"),
    path('create_api/', views.create_api, name='create_api'),
    path('', views.dash_rdrct, name='dashboardu'),
    re_path(r'^configure_api/(?P<proj_id>\d+)/(?P<api_id>\d+)$', views.configure_api, name='configure_api'),
    path("change/pass", views.change_password, name="change_pass"),
    
    re_path(r'^adding_api/(?P<proj_id>\d+)/(?P<id>\d+)$', views.adding_api, name='adding_api'),
    re_path(r'^activate/(?P<proj_id>\d+)/(?P<id>\d+)$', views.activate_api, name='activate_api'),
    # re_path(r'(?P<project_name>\w+)$', views.api_list, name='dashboard'),
    # re_path(r'(homepage/?P<name>\d+)$', views.home_page, name='home_page'),
    # re_path(r'^switch/(?P<id>\d+)$', views.switch, name='switch'),
    # re_path(r'^rmv_api/(?P<id>\d+)$', views.rmv_api, name='rmv_api'),
    
    path('logout/', views.logout, name='logout'),
    path('settings/', views.settings, name='settings'),
    path('addProject/', views.addProject, name='addProject'),
    path('create_api_page/', views.create_api_page, name='create_api_page'),
    path('delete/<int:id>', views.delete_project, name='delete_project'),
    # re_path(r'^addProject/(?P<id>\d+)$', views.addProject, name='addProject'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.core.mail import send_mail
import requests
from user_dashboard.models import Api
# Home page view


def index(request):
    all_apis = Api.objects.order_by('title')
    return render(request, 'homepage/index.html', {'all_apis':all_apis})


# About us view
def about(request):
    return render(request, 'homepage/about.html')


# Contact us page
def contact_us(request):
    """Sends an email to admin with user's data from the frontend"""
    if request.method == "POST":
        if request.POST.get("submit"):
            name = request.POST.get("name")
            email = request.POST.get("email")
            message = request.POST.get("message")
            admin = "immanuelhng@gmail.com"

            # validation and sending an email with the email microapi
            if name and email and message:
                url = "https://email.microapi.dev/v1/sendmail/"
                response = requests.post(url, data={
                    "recipient": admin,
                    "sender": "phemmylintry@gmail.com",
                    "subject": (email + '\n' + name),
                    "body": message,
                    "cc": "",
                    "bcc": ""}
                )
    return render(request, 'homepage/contact.html')


# Views to FAQ
def faq(request):
    return render(request, 'homepage/faq.html')


# views to recover password
def recover_password(request):
    return render(request, 'accounts/recover_password.html')

# views to recover password


def reset_link(request):
    return render(request, 'accounts/reset_link_sent.html')

# views to recover password


def reset_password(request):
    return render(request, 'accounts/reset_password.html')

  
def blog_list(request):
    return render(request, 'blog/blog_listing.html')
  
def blog_post(request):
    return render(request, 'blog/blog_post.html')

def blog_search(request):
    return render(request, 'blog/blog_search.html')

templates/homepage/about.html
{% extends 'homepage/base.html'%}

{% load static %}
{% block content %}

    <body id="about">
    
    <!-- Main body goes here -->
    <div class="content">
        <div class="inner-content-1">
            <h1 >About Us</h1>

            <h3 >Who we are?</h3>

            <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Odio condimentum aenean aenean ut. Id quis nulla aliquam et rutrum egestas purus. Egestas quis eget amet fermentum erat. Blandit id nunc phasellus ac. Luctus nunc dolor imperdiet facilisi leo, cursus. Pulvinar eget nisi libero turpis commodo.</p>
        </div>

        <div class="inner-content-2">
            <div class="inner-content2-txt">
                <h4>Our Sevices</h4>
            <div class="content-list">
                <h5>1. API</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Odio condimentum aenean aenean ut. Id quis nulla aliquam et rutrum egestas purus. Egestas quis eget amet fermentum erat. Blandit id nunc phasellus ac. Luctus nunc dolor imperdiet facilisi leo, cursus. Pulvinar eget nisi libero turpis commodo.</p>
            </div>

            <div class="content-list">
                <h5>2. Micro-services</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Odio condimentum aenean aenean ut. Id quis nulla aliquam et rutrum egestas purus. Egestas quis eget amet fermentum erat. Blandit id nunc phasellus ac. Luctus nunc dolor imperdiet facilisi leo, cursus. Pulvinar eget nisi libero turpis commodo.</p>
            </div>

            <div class="content-list">
                <h5>3. Integration</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Odio condimentum aenean aenean ut. Id quis nulla aliquam et rutrum egestas purus. Egestas quis eget amet fermentum erat. Blandit id nunc phasellus ac. Luctus nunc dolor imperdiet facilisi leo, cursus. Pulvinar eget nisi libero turpis commodo.</p>
            </div>
            </div>
        </div>
    </div>
    </body>
{% endblock %}

templates/homepage/base.html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here" />
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
<!--<link rel="stylesheet" href="assets/css/style.min.css">-->
<link rel="stylesheet" href="{% static 'css/style.min.css' %}">
<title>Micro Api - Layout</title>
</head>

<body>
  <!--Other pages inherit the header and footer from this page-->
  <header>
    <!-- Write header here -->
    <div class="container">
      <div class="row pt-4 pb-4 header__wrapper">
        <div class="col-lg-2 col-md-6 col-sm-6 logo__container">
          <a href="{% url 'index' %}" class="logo"><img src="{% static 'img/logo.svg' %}" alt="site logo"></a>
        </div>

        <nav class="col-lg-6">
			  <ul class="nav__menu">
			  <li><a href="{% url 'index' %}">Home</a></li>
			  <li><a href="{% url 'about' %}">About us</a></li>
			  <li><a href="{% url 'contact' %}">Contact us</a></li>
        <li><a href="#">Documentation</a></li>
        <li><a href="{% url 'blog' %}">Blog</a></li>
			</ul>
      </nav>
        <div class="col-lg-4 menu__button__container">

        {% if user.is_authenticated %}
          <a href="{% url 'user_dashboard:dashboardu' %}"><button class="secondary-btn">Dashboard</button></a>
          <a href="{% url 'accounts:signout' %}"><button class="primary-btn">Sign Out</button></a>
        {% else %}
          <a href="{% url 'accounts:signin' %}" button class="secondary-btn">Sign In</button></a>
          <a href="{% url 'accounts:signup' %}"><button class="primary-btn">Sign Up</button></a>
        {% endif %}        
          
        </div>

        <div class="mobile__nav">
          <div class="hamburger">
            <div></div>
            <div></div>
            <div></div>
          </div>

          <div class="mobile__menu">
            <nav class="nav">
              <div class="search__form">
                <label for="search">
                  <input type="text" name="search" placeholder="Search...">
                </label>
                <div class="search__icon">
                  <i class="fas fa-search"></i>
                </div>
              </div>

              <ul class="mobile__nav__menu">
                <li><a href="{% url 'index' %}"><b>Home</b></a></li>
                <li><a href="{% url 'about' %}"><b>About us</b></a></li>
                <li><a href="{% url 'contact' %}"><b>Contact us</b></a></li>
                <li><a href="#"><b>Documentation</b></a></li>
                <li><a href="{% url 'blog' %}"><b>Blog</b></a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:signout' %}"><b>Sign Out</b></a></li>
                {% else %}
                <li><a href="{% url 'accounts:signin' %}"><b>Sign in</b></a></li>
                <li><a href="{% url 'accounts:signup' %}"><b>Sign Up</b></a></li>
                {% endif %}  
                <li>
                  <a href="#"><i class="fab fa-facebook-f"></i></a>
                  <a href="#"><i class="fab fa-instagram"></i></a>
                  <a href="#"><i class="fab fa-twitter"></i></a>
                </li>
              </ul>

              <div class="menu__logo">
                <a href="#"><img src="{% static 'img/logo.svg' %}" alt=""></a>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </header>


  {% block content %}
  {% endblock %}


  <footer>
    <!-- Write footer here -->
    <div class="container pt-5 pb-5 footer__wrapper">
      <div class="footer__logo__container">
        <div class="footer__logo">
          <a href="#"><img src="{% static 'img/logo.svg' %}" alt="footer logo"></a>
        </div>
      </div>

      <div class="footer__menus__container">
        <div>
          <h6>Product</h6>
          <ul>
            <li><a href="#">Authentication API</a></li>
            <li><a href="#">Models</a></li>
            <li><a href="{% url 'faq' %}">FAQ</a></li>
          </ul>
        </div>

        <div>
          <h6>Collaboration</h6>
          <ul>
            <li><a href="#">Comments</a></li>
            <li><a href="#">Track Changes</a></li>
          </ul>
        </div>

        <div>
          <h6>Explore</h6>
          <ul>
            <li><a href="{% url 'contact' %}">Contact Us</a></li>
            <li><a href="{% url 'about' %}">About Us</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <script src="{% static 'js/nav.js' %}"></script>
  <script>
    $('#pwd, #confirmpwd').on('keyup', function () {
    if ($('#pwd').val() == $('#confirmpwd').val()) {
      $('#message').html('').css('color', 'green');
    } else 
      $('#message').html('Passwords do not match').css('color', 'red');
  });
  </script>
</body>
</html>

templates/homepage/contact.html
{% extends 'homepage/base.html'%}

{% block content %}
{% load static %}

<body id="contact">

  <!-- Main body goes here -->

  <div class="contact container-fluid">
    <div class="contact__header col text-center">
      <h1>
        Contact Us
      </h1>
    </div>
    <div class="contact__intro col col-12 col-md-8 col-lg-4">
      <p>
        We’d love to hear from you! Let us know what you think–feel free to chat with us, tweet at us, or get in
        touch
        with
        support.
      </p>
    </div>
    <div
      class="contact__main row col-lg-7 col-xl-6 mx-auto d-flex flex-column-reverse flex-md-row justify-content-around align-items-start">
      <div class="contact__details col-12 mt-5 mt-md-0 col-md-5 col-lg-6 px-0">
        <h4>
          We'd love to hear from you
        </h4>
        <div class="details mb-3">
          <span class="fa fa-map-marker-alt mr-3"></span>
          <span>HNG Road, 315 Work Avenue</span>
        </div>
        <div class="details mb-3">
          <span class="fa fa-phone mr-3"></span>
          <span>
            <a class="detail__link" href="tel:+2348102557945">(0)-810-255-7945</a>
          </span>
        </div>
        <div class="details mb-3">
          <span class="fa fa-envelope mr-3"></span>
          <span>
            <a class="detail__link" href="mailto:microapi@sample.com">microapi@sample.com</a>
          </span>
        </div>
      </div>
      <div class="contact__form col-12 col-md-6 px-0">
        <form method="POST" action="#">
          {% csrf_token %}
          <input type="text" name="name" value="" id="name" placeholder="Name" class="form__element">
          <input type="email" name="email" value="" id="mail" placeholder="Email" class="form__element">
          <textarea name="message" value="message" id="message" rows="10" placeholder="Write something..."
            class="w-100 form__element"></textarea>
          <button type="submit" name="submit" value="OK" class="primary-btn form__element">Submit</button>
        </form>
      </div>
    </div>
  </div>
</body>
{% endblock %}

</html>

templates/homepage/faq.html
{% extends 'homepage/base.html' %}

{% block content %}
{% load static %}
	<body id="faq">
	<!-- Main body goes here -->
	<div class="block">
			<div class="block__banner">
				<h1>Frequently <br>asked questions</h1>
			</div>
			<div class="block__mainsection">
				<div class="block__question">
					<h4 class="block__question__header">Is this thing on?
						<span class="block__question__header__btn"><i class="fas fa-angle-right"></i></span>
					</h4>
					<p class="block__question__answer">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				</div>
				<div class="block__question">
					<h4 class="block__question__header">Is this thing on?
						<span class="block__question__header__btn"><i class="fas fa-angle-right"></i></span>
					</h4>
					<p class="block__question__answer">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				</div>
				<div class="block__question">
					<h4 class="block__question__header">Is this thing on?
						<span class="block__question__header__btn"><i class="fas fa-angle-right"></i></span>
					</h4>
					<p class="block__question__answer">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				</div>
				<div class="block__question">
					<h4 class="block__question__header">Is this thing on?
						<span class="block__question__header__btn"><i class="fas fa-angle-right"></i></span>
					</h4>
					<p class="block__question__answer">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				</div>
				<div class="block__question">
					<h4 class="block__question__header">Is this thing on?
						<span class="block__question__header__btn"><i class="fas fa-angle-right"></i></span>
					</h4>
					<p class="block__question__answer">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				</div>
				<div class="block__question">
					<h4 class="block__question__header">Is this thing on?
						<span class="block__question__header__btn"><i class="fas fa-angle-right"></i></span>
					</h4>
					<p class="block__question__answer">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				</div>
			</div>
		</div>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
	<script type="text/javascript" src="{% static 'js/faq.js' %}"></script>
	</body>
{% endblock %}

templates/homepage/index.html
{% extends 'homepage/base.html' %}

{% block content %}
{% load static %}
  <body id="home">
    
    <main>
      <section>
          <div class="container-fluid">
              <div class="row item-one ">
                <div class="col-md-12 text-center">
                  <h1 class="item-one__header">Open Source APIs for</h1>
                  <h1 class="item-one__header">Individuals and Enterprises </h1>
                  <p class="item-one__text">MicroAPi is a library of microservice APIs, built and organized <br>for your software team to get that project running.</p>
                </div>
              </div>
              <div class="row dashboard">
                <div class="col-md-12 text-center dashboard__container">
                  <img class="dashboard__container__img" src="{% static 'img/Group 645.png' %}" alt="placeholder">
                </div>
              </div>
              <div class="row item-two mt-5">
                <div class="col-md-12 text-center">
                  <h1 class="item-one__header">The best open source micro service</h1>
                  <p class="item-four__description item-one__text" >We make it easy for you or your co-operation to build and organize your<br> database seemlessly at speeds you could only dream about </p>
                </div>
              </div>
              <div class="my-4 item-three text-center">
                <h5>Why MicroAPI ?</h5>
              </div>
              <div class="container">
                <div class="row mt-3 item-four">
                  <div class="col-md-3 item-four__content">
                    <h6 class="item-four__header text-center">No-Code Tool</h6>
                    <p class="item-four__description">Build amazing apps faster. Our API saves you months of integration testing and support headache for you and your customers. </p>
                  </div>
                  <div class="col-md-3 item-four__content"> 
                    <h6 class="item-four__header text-center">Fast Implementation</h6>
                    <p class="item-four__description">Build amazing apps faster. Our API saves you months of integration testing and support headache for you and your customers. </p>
                  </div>
                  <div class="col-md-3 item-four__content"> 
                    <h6 class="item-four__header text-center">Easy to use</h6>
                    <p class="item-four__description">Build amazing apps faster. Our API saves you months of integration testing and support headache for you and your customers. </p>
                  </div>
                </div>
            </div>
            
            <div class="container-fluid item-five">
              <div class="row ">
                <div class="col-md-12 mb-5"> 
                  <div class="container heading">
                    <h2 class="item-one__header">Dashboard that works</h2>
                  <p class="item-one__text"> MicroAPI provides you with a dashboard that is simple and easy to navigate, allowing you drag 
                    and drop your APIs at ease. It is designed to help you 
                    curate your website, work on them and publish as you please.</p>
                  </div>
                    <div class="item-five__container">
                    <img class="img-fluid item-five__image-container__img" src="{% static 'img/Group 596.png' %}" alt="placeholder">  
                  </div>
                </div>      
              </div>
            </div>

            <div class="container">
              <div class="row">
                <div class="col-md-12 mt-5 mb-3 item-ten"> 
                  <h5 class="text-center item-ten__text">Integrates well with your git provider</h5>
                </div>
                <div class=" item-six">
                  <a href="#"><i class="fab fa-github fa-3x py-3 item-six__icon"></i></a>
                  <a href="#"><i class="fab fa-gitlab fa-3x  py-3 item-six__icon"></i></a>
                  <a href="#"><i class="fab fa-bitbucket fa-3x  py-3 item-six__icon"></i></a>
                </div> 
              </div>
              <!-- <div class="row"> -->
                    
              
            </div>


            <div class="container-fluid item-seven">
              <div class="row  ">
                <div class="col-md-12 mb-5"> 
                  <div class="container heading">
                    <h2 class="item-one__header">Dashboard that works</h2>
                    <p class="item-one__text"> MicroAPI provides you with a dashboard that is simple and easy to navigate, allowing you drag 
                      and drop your APIs at ease. It is designed to help you 
                      curate your website, work on them and publish as you please.</p>
                  </div>
                    <div class="item-seven__container">
                      <img class="img-fluid item-five__image-container__img" src="{% static 'img/Group 623.png' %}" alt="placeholder">
                    </div>
                  </div>
                </div>      
              </div>


              <div class="item-ten__other">
                <div class="col-md-12 my-5 item-ten"> 
                  <h5 class="text-center item-ten__text">Seamless integration with your favorite frameworks</h5>
                </div>
                <div class="item-ten__image-container">
                <div>
                  <img class="img-fluid  item-ten__image-container__img" src="{% static 'img/react-icon.png' %}">
                </div>
                <div>
                 <img class="img-fluid  item-ten__image-container__img" src="{% static 'img/ember-icon.png' %}">
                </div>
                <div>
                 <img class="img-fluid  item-ten__image-container__img" src="{% static 'img/angular-icon.png' %}">
                </div>
                <div>
                  <!-- <img class="img-fluid  item-ten__image-container__img" src="{% static 'img/gatsby-icon.png' %}"> -->
                </div>
              </div>
            </div>

            <div class="container-fluid mt-5 item-eight">
              <div class="container">
                <div class="row py-5">
                  <div class="col-md-12 text-center">
                    <h1 class="item-one__header">Available APIs</h1>
                    <p  class="item-one__text">Here’s a list of APIs that we currently have for you, we’ll be adding more in subsequent times</p>
                  </div>
                </div>
              </div>
            </div> 
            <div class="container-fluid">
              <div class="text-danger text-center">
                  {% for message in messages %}
                    {{ message }}
                  {% endfor %}
              </div>
              <div class="container item-nine">
                {% if all_apis %}
                  {% for api in all_apis %}
                    <div class="col-md-6 item-nine__content">
                      <div class="item-nine__item mb-5">
                        <h2 class="item-one__header">{{ api.title }}</h2>
                        <p class="item-one__text">{{ api.description }}</p>
                        <a href="{% url 'docs' api.slug %}" class="item-nine__item__link item-one__text">View Documentation</a>
                      </div>
                    </div>
                  {% endfor %}
                {% else %}
                  <div class="container">
                    <div class="row py-5">
                      <div class="col-md-12 text-center">
                        <h1 class="item-one__header">No Available APIs at the moment!</h1>
                        <h1 class="item-one__header">COMING SOON!</h1>
                      </div>
                    </div>
                  </div>
                {% endif %}
              </div>
            </div>
        
            <div class="container-fluid mt-5 item-eleven">
              <div class="container">
                <div class="row">
                  <div class="col-md-12 mb-5 text-center">
                    <h1 class="mb-5 item-one__header">Make your work seamless</h1>
                    <input type="text" placeholder="Enter Your email">
                    <button href="#" class="started_btn">Get Started</button>
                    <!-- <a href="#" class="item-nine__button">Get Started</a> -->
                  </div>
                  <form>
              
         

                </div>
              </div>
            </div> 

            
          </div>
      </section>
    </main>
  </body>
{% endblock %}