accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    # path('successCallback/', views.successCallback, name='successCallback'),
    # path('failureCallback/', views.failureCallback, name='failureCallback'),
    # path('oauth2callback/')
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    # path('oauth2callback/', views.oAuth2CallBackView, name="oauth2callback"),
    # path('recover/', views.pass_recovery, name='recover'),
    # path('logout', views.logout, name="logout"),
    # path('recover/sent', views.sent_link, name='sent-link'),
    # path("reset", views.reset_password, name="reset-password"),
    path('signout/', views.signout, name='signout')
]

microapi_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homepage.urls")),
    # path('blog/', include('blog')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('dashboard/', include('user_dashboard.urls', namespace="dashboard")),
    path('', include("api_docs.urls")),
    path('accounts/', include('allauth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_dashboard/urls.py
from django.urls import path, re_path
from . import views

app_name = "user_dashboard"

urlpatterns = [
    path("main/", views.dash, name="dash_main"),
    path("main/<str:name>", views.oneproj, name="dash_proj"),
    path('create_api/', views.create_api, name='create_api'),
    path('', views.dash_rdrct, name='dashboardu'),
    re_path(r'^configure_api/(?P<proj_id>\d+)/(?P<api_id>\d+)$', views.configure_api, name='configure_api'),
    path("change/pass", views.change_password, name="change_pass"),
    
    re_path(r'^adding_api/(?P<proj_id>\d+)/(?P<id>\d+)$', views.adding_api, name='adding_api'),
    re_path(r'^activate/(?P<proj_id>\d+)/(?P<id>\d+)$', views.activate_api, name='activate_api'),
    # re_path(r'(?P<project_name>\w+)$', views.api_list, name='dashboard'),
    # re_path(r'(homepage/?P<name>\d+)$', views.home_page, name='home_page'),
    # re_path(r'^switch/(?P<id>\d+)$', views.switch, name='switch'),
    # re_path(r'^rmv_api/(?P<id>\d+)$', views.rmv_api, name='rmv_api'),
    
    path('logout/', views.logout, name='logout'),
    path('settings/', views.settings, name='settings'),
    path('addProject/', views.addProject, name='addProject'),
    path('create_api_page/', views.create_api_page, name='create_api_page'),
    path('delete/<int:id>', views.delete_project, name='delete_project'),
    # re_path(r'^addProject/(?P<id>\d+)$', views.addProject, name='addProject'),
]

user_dashboard/models.py
from django.db import models
from django.contrib.auth import get_user_model
from accounts.models import User
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.core.serializers.json import DjangoJSONEncoder
import json

class JSONField(models.TextField):
    def to_dict(self, value):
        return json.loads(value)

    def to_json(self, value):
        return json.dumps(value)

    def to_python(self, value):
        if value == "":
            return None
        try:
            if isinstance(value, str):
                return self.to_dict(value)
        except ValueError:
            pass
        return value

    def from_db_value(self, value, *args):
        return self.to_python(value)

    def get_db_prep_save(self, value, *args, **kwargs):
        if value == "":
            return None
        if isinstance(value, dict):
            value = json.dumps(value, cls=DjangoJSONEncoder)
        return value

#Models for all the API's in the database
class Api(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    icon = models.CharField(max_length=255, default='icon')
    slug = models.SlugField(null=False, unique=True, default=title)
    docs_url = models.CharField(max_length=255,default='')
    # stats = models.CharField(max_length=255, default='3req/hr')
    get_settings = models.URLField(blank=True)
    post_settings = models.URLField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
    #is_active = models.BooleanField("api_status", default=False)
    #project = models.ManyToManyField(Project, related_name='project_api', blank=True)
    #project = models.ForeignKey(Project, related_name='UserApis', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('docs', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
          
# class Configs(models.Model):
#     konfigs = JSONField(null=True, blank=True)
#     konfigd_api = models.ForeignKey(Api, related_name='configurations', on_delete=models.CASCADE)
#     created_on = models.DateTimeField(auto_now_add=True)
#     updated_on = models.DateTimeField(auto_now_add=True)  
#     #
#     def __str__(self):
#         return 'configurations'


class Project(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE,)
    token = models.UUIDField(null=True, blank=True)
    api_settings = JSONField(null=True, blank=True)
    project_api = models.ManyToManyField(Api, through='Configs' , related_name='project_api', blank=True)
    last_project = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

    def add_api(api, projet):
        if api in projet.project_api.all():
            projet.project_api.remove(api)
            message = "Removed"
            return message
        else:
            projet.project_api.add(api)
            message = "Added"
            return message
    #Keep track of lastProject
    def save(self, *args, **kwargs):
        if self.last_project:
            try:
                temp = Project.objects.get(last_project=True)
                if self != temp:
                    temp.last_project = False
                    temp.save()
            except Project.DoesNotExist:
                pass
        super(Project, self).save(*args, **kwargs)

class Configs(models.Model):
    konfigs = JSONField(null=True, blank=True)
    project = models.ForeignKey(Project,related_name='configurations', on_delete=models.CASCADE)
    konfigd_api = models.ForeignKey(Api, related_name='configurations', on_delete=models.CASCADE)
    is_active = models.BooleanField("api_status", default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)  

    def __str__(self):
        return 'configurations'
        

user_dashboard/views.py
import json
from django.shortcuts import render, redirect, HttpResponseRedirect,HttpResponse
from django.views.generic import TemplateView, ListView
from . models import Api, Project, Configs
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from homepage.views import index
import uuid
from django.conf import settings
from django.contrib import messages
import requests
from user_dashboard.models import Project
from django.contrib.auth.views import logout_then_login
from django.core.exceptions import ValidationError, ObjectDoesNotExist
import urllib.parse
from user_dashboard.models import Project, Api
from django.shortcuts import get_object_or_404
#

# HEADERS = {
#     "Authorization": "Bearer %s" % (settings.AUTH_ADMIN_TOKEN)
# }

# BASE_URL = settings.AUTH_API_URL


@login_required(login_url='/accounts/signin')
def dash_rdrct(request):
    user = request.user
    proj_name = Project.objects.filter(user=user).get(last_project=True)
    
    if proj_name is not None:
        proj_name = proj_name.name
    else:
        proj_name = Project.objects.create(
        name="Default_Project", user=user, token=uuid.uuid4().hex, last_project=True)
        proj_name.save()
        proj_name.name = user.last_project
        user.save()
    return redirect('/dashboard/main/' + '{}'.format(proj_name))
    # return redirect('/dashboard/')

#new Dashboard
@login_required(login_url='/accounts/signin')
def dash(request):
    user = request.user
    projects = Project.objects.filter(user=user)
    context = {
        'projects' : projects
    }
    return render(request, 'user_dashboard/dashboard.html', context)

#ProjPage
@login_required(login_url='/accounts/signin')
def oneproj(request, name):
    try:
        user= request.user
        projects = Project.objects.filter(user=user)
        user_proj = Project.objects.filter(user=user).filter(name=name)
        spef_proj = Project.objects.filter(user=user).get(name=name)
        api_list = Api.objects.all()
        spef_proj.last_project = True
        spef_proj.save()
        pe = Configs.objects.filter(project=spef_proj)
    except Project.DoesNotExist:
        messages.info(request, f"Project {name} does not exist..Add a new project")
        return redirect('user_dashboard:settings')


    context = {
        'projects' : projects,
        'user_proj': user_proj,
        'api_list': api_list,
        'spef_proj':spef_proj,
        'pe':pe,
    }

    return render(request, 'user_dashboard/project.html', context)



@login_required(login_url='/accounts/signin')
def api_list(request, project_name):
    print(request)
    # proj = Project.objects.get(name=project_name)
    path = request.path
    get_id = str([i for i in str(path).split('/') if i][-1])
    projet = request.user.projects.get(name=get_id)
    print(projet)
    all_apis = Api.objects.order_by('title')
    print(all_apis)
    return render(request, 'user_dashboard/dashboard.html', {'all_apis':all_apis, 'projet':projet})

def adding_api(request, proj_id, id):
    add_to_api = Api.objects.get(id=id)
    print(add_to_api)
    project = Project.objects.get(id=proj_id)
    print(project)
    Project.add_api(api=add_to_api, projet=project)
    #all_apis = objects.order_by('title')
    pro_id = project.name
    print(pro_id)
    return redirect('/dashboard/main/' + '{}'.format(pro_id))
    #return render(request, 'user_dashboard/dashboard.html', {'all_apis':all_apis})

def activate_api(request, proj_id, id):
        print(request.POST)
        pj = Project.objects.get(id=proj_id)
        api = pj.project_api.get(id=id)
        pe = Configs.objects.filter(project=pj).get(konfigd_api=api)
        #api = ApiList.objects.get(id=id)
        print(pj)

        if request.POST.get('active') == 'true':
            pe.is_active = True
            pe.save()
            print(pe.is_active)
            return JsonResponse({'status':'Active'})
        pe.is_active = False
        pe.save()
        print(pe.is_active)
        return JsonResponse({'status':'De-Activated'})

@login_required(login_url='/accounts/signin')
def configure_api(request, proj_id, api_id):
    projects = Project.objects.filter(user=request.user)
    pro_name = Project.objects.filter(user=request.user).get(id=proj_id)
    api_to_conf = pro_name.project_api.get(id=api_id)
    name = api_to_conf.title
    inst = Configs.objects.filter(project=pro_name).get(konfigd_api=api_to_conf)
    
    edit_settings = dict()
    try:
        docs = get_object_or_404(Api, id=api_id)
        api_docs = docs.docs_url
        response = requests.get(api_docs)
        documentation = response.json()
        servers = documentation['data']['servers']
        paths = documentation['data']['paths']
        server_url = servers[0]['url']
        if request.method == 'POST':
            dicto = request.POST
            user_settings = dicto.dict()
            del user_settings['csrfmiddlewaretoken']
            print(user_settings)

            # configs = Configs.objects.filter(konfigs=None, project=pro_name).get(konfigd_api=api_to_conf)
            # print(configs)
            
            # save = request.POST.get('save')
            # print(save)
            # update = request.POST.get('update')
            # create = request.POST.get('create')

            print(name, "line 147")
            if name.upper() == 'SMS MICROAPI':
                print('something')
                sender = user_settings['sender']
                service_name = user_settings['service_name'] 
                token = user_settings['token'] 
                sid = user_settings['sid'] 
                verified_no = user_settings['verified_no'] 
                default = user_settings['default'] 
                
                headers = {}
                payload = {
                    "sender": f'{sender}',
                    "service_name": f'{service_name}',
                    "token": f'{token}',
                    "sid": f'{sid}',
                    "verified_no": f'{verified_no}',
                    "default": f'{default}'
                }

                payload2 = {
                    "senderID": f'{sender}'
                }
                
                if 'save_btn' in request.POST:
                    url = api_to_conf.post_settings
                    del user_settings['save_btn']
                    register = requests.request('POST', 'https://sms-microapi.herokuapp.com/v2/sms/user_register', headers=headers, data=payload2)
                    reg = register.json()
                    print(reg)
                    response = requests.request('POST', url, headers=headers, data=payload)
                    print(response)
                    response = response.json()
                    msg = response['details']
                    print(msg)
                    if response['status'] == 201:
                        print('something')
                        specf_set = dict()    
                        inst.konfigs = user_settings
                        inst.save()
                        messages.success(request, "you've successfully configured {}|{}".format(name, msg))
                        return redirect('/dashboard/main/' + '{}'.format(pro_name.name), {'paths' : paths,'url' : server_url})
                    else:
                        messages.success(request, f"{msg}")
                        return redirect('/dashboard/main/' + '{}'.format(pro_name.name), {'paths' : paths,'url' : server_url})
                
                elif 'update_btn' in request.POST:
                    print('yes')
                    url = 'https://sms-microapi.herokuapp.com/v2/sms/config/update_config'
                    del user_settings['update_btn']
                    response = requests.request('PUT', url, headers=headers, data=payload)
                    response = response.json()
                    msg = response['details']
                    # print(response)
                    if response['status'] == 202:
                        # specf_set = dict()    
                        print('yessss')
                        first_time = True
                        edit_settings = dict()
                        print(edit_settings)
                        print(inst.konfigs)
                        print(user_settings)

                        inst.konfigs = user_settings
                        inst.save()
                        messages.success(request, "you've successfully updated {}|{}".format(name, msg))
                        return redirect('/dashboard/main/' + '{}'.format(pro_name.name), {'paths' : paths,'url' : server_url})
                    else:
                        messages.success(request, f"{msg}")
                        return redirect('/dashboard/main/' + '{}'.format(pro_name.name), {'paths' : paths,'url' : server_url})
                
                elif 'create_btn' in request.POST:

                    url = api_to_conf.post_settings
                    del user_settings['create_btn']
                    response = requests.request('POST', url, headers=headers, data=payload)
                    print(response)
                    response = response.json()
                    msg = response['details']
                    print(msg)
                    if response['status'] == 201:
                        print('something')
                        specf_set = dict()    
                        inst.konfigs = user_settings
                        inst.save()
                        messages.success(request, "you've successfully configured {}|{}".format(name, msg))
                        return redirect('/dashboard/main/' + '{}'.format(pro_name.name), {'paths' : paths,'url' : server_url})

templates/user_dashboard/create_api.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="Description" content="Enter your description here" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css">
  <link rel="stylesheet" href=" https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="{% static 'css/style.min.css'%}">
  <title>MicroAPI - Dashboard</title>
</head>

<body>
<form action="{% url 'dashboard:create_api' %}" method="POST">
{% csrf_token %}
    <div class="form-group">
        <label for="Info Url"></label>
        <input type="text" class="form-control" name="info_url" id="" aria-describedby="helpId" placeholder="Info Url">
        <input type="text" class="form-control" name="docs_url" id="" aria-describedby="helpId" placeholder="Docs Url">
        <input type="text" class="form-control" name="settings_url" id="" aria-describedby="helpId" placeholder="Get Settings Url">
        <input type="text" class="form-control" name="post_settings" id="" aria-describedby="helpId" placeholder="Post Settings Url">
        <small id="helpId" class="form-text text-muted" style="margin-bottom: 15px;"></small>
        <a href=""><button type="submit" class="btn btn-primary">Create API</button></a>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
    </div>
</form>

{% comment %} <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>  -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="{% static 'js/dashboard_sidebar.js' %}"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
<script src="{% static 'js/configure_api.js' %}"></script>
<script src="{% static 'js/acct-settings.js' %}"></script>
{% block javascript %} {% endblock %} {% endcomment %}
</body>

</html>

templates/user_dashboard/dash_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="Description" content="Enter your description here" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css">
  <link rel="stylesheet" href=" https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="{% static 'css/style.min.css'%}">
  <title>MicroAPI - Dashboard</title>
</head>

<body>
  <!-- dashbord -->
  <div id="dashboard">
    <!-- dashboard side bar -->
    <div class="sidebar">
      <div class="sidebar__logo">
        <a href=""><img src="{% static 'img/logo-alt.svg' %}" alt=""></a>
      </div>

      <div class="sidebar__section">
        <div class="sidebar__section__header">
          <h5>Projects <i class="fas fa-angle-up"></i></h5>
          <ul class="sidebar__section__header__list">
            <!-- {% for project in user.projects.all %}
              <li>
                <a href="{% url 'user_dashboard:dashboardu' %}">{{ project.name }}</a>
                <div class="pretty p-icon">
                  <input type="checkbox" />
                  <div class="state">
                    <i class="icon material-icons">done</i>
                    <label><span class="spacer"></span>Acme Project's</label>
                  </div>
                </div> -->
              <!-- </li> -->
            <!-- {% endfor %} --> 
            <!-- {% for project in user.projects.all %}
              <li>
                <a href="{% url 'user_dashboard:dashboardu' %}">{{ project.name }}</a>
                <div class="pretty p-icon">
                  <input type="checkbox" />
                  <div class="state">
                    <i class="icon material-icons">done</i>
                    <label><span class="spacer"></span>Acme Project's</label>
                  </div>
                </div>
              </li>
            {% endfor %} -->
            {% for item in projects %}
            <li>
 
              <a href="{% url 'user_dashboard:dash_proj' item.name%}">{{ item.name }}</a>
            </li>

            {% endfor %}

            <!-- <li>
              <a href="#" class="inactive">Sentry's Prrojects</a>

             <div class="pretty p-icon">
                <input type="checkbox" />
                <div class="state">
                  <i class="icon material-icons">done</i>
                  <label><span class="spacer"></span>Sentry Project's</label>
                </div>
              </div> -->

            <button class="add-new" type="button" class="btn btn-primary" data-toggle="modal" data-target="#addApiModal">
              <span>+</span>
              <a href="#">New project</a>
            </button>

            <!-- Modal -->
            <div class="modal fade" id="addApiModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static" data-keyboard="false">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Add Project</h5>
                    <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button> -->
                  </div>
                  <div class="modal-body">

                    <form action="{% url 'dashboard:addProject' %}" method="POST">
                    {% csrf_token %}
                      
                    <div class="form-group">
                      <label for="project name">
                        <input type="text"
                        class="form-control" name="project_name" id="" required aria-describedby="helpId" placeholder="Enter project name">
                      </label>
                      

                      <div class="modal-foot">
                        <button type="button" class="btn" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn">Add Project</button>
                      </div>

                    </div>

                    </form>


                  </div>
                  <!-- <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Add Project</button>
                  </div> -->
                </div>
              </div>
            </div>
            <!-- Modal end -->
          </ul>
        </div>
        <div class="sidebar__section__content">
          <div class="sidebar__section__content__sub">
            <h5>Tools <i class="fas fa-angle-up"></i></h5>
            <ul class="sidebar__section__content__sub__list">
              <li>
                <a href="#">MicroAPIs</a>
              </li>
              <li>
                <a href="#">Frontends</a>
              </li>
              <li>
                <a href="#">Database</a>
              </li>
            </ul>
          </div>
          <div class="sidebar__section__content__sub">
            <h5 class="sidebar__section__content__sub__title">Accounts <i class="fas fa-angle-up"></i></h5>
            <ul class="sidebar__section__content__sub__list">
              <li>
                <a href="{% url 'dashboard:settings' %}">Account settings</a>
              </li>
              <li>
                <p><a href="{% url 'accounts:signout' %}">Sign out</a></p>
              </li>
            </ul>
          </div>
          <div class="sidebar__section__content__sub">
            <h5 class="sidebar__section__content__sub__title">Contribute <i class="fas fa-angle-up"></i></h5>
            <ul class="sidebar__section__content__sub__list">
              <li>
                <a href="#">Contribute to MicroAPI</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="content">
      <header>
        <a class="menu"><i class="fas fa-bars"></i></a>
        <div class="profile_section">

          <div class="back__container">
            <a href="#" class="tetiary-btn back-btn"><i class="fas fa-angle-left"></i> Back</a>
          </div>

          <a type="button" data-toggle="modal" data-target="#notificationModal"><i class="far fa-bell"></i></a>
          
          <!-- Modal -->
          <div class="modal fade" id="notificationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="false" data-keyboard="false">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">All Notifications</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="notification-content">
                    <div class="empty-notifications">
                      <span class="material-icons">notifications_paused</span>
                      <h3>Nothing to see here</h3>
                      <p>You do not have any new notifications. Check back later when you have some activity</p>
                    </div>
                  </div>

                </div>
                <!-- <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                  <button type="button" class="btn btn-primary">Add Project</button>
                </div> -->
              </div>
            </div>
          </div>
          <!-- Modal end -->

          <div class="profile_section__pix">{{user.username}}<a href="{% url 'dashboard:settings' %}"><img src="{{ user.image }}" alt=""></a></div>
        </div>
      </header>

  {% block content %}


  {% endblock %}
  

<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>  -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="{% static 'js/dashboard_sidebar.js' %}"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
<script src="{% static 'js/configure_api.js' %}"></script>
<script src="{% static 'js/acct-settings.js' %}"></script>
{% block javascript %} {% endblock %}
</body>

</html>

templates/user_dashboard/switch_project.html
{% extends 'user_dashboard/dash_base.html' %}

{% block content %}
{% load static %}

<div id="settings">

  <div>
    <div class="main__title">
      <h1>Account Settings</h1>
      <p>Set your preference, help us personalize your experience and make account changes here</p>
    </div>

    <div class="main__content__heading">
      <div></div>

      <div>
        <h4>Profile</h4>
      </div>
    </div>

    <div class="main__content">
      <div class="main__content__menu">
        <ul>
          <li class="active"><b>Profile</b></li>
          <li><b>Password</b></li>
          <li><b>Projects</b></li>
        </ul>
      </div>

      <section class="main__content__tabs">
        
        <article id="profile-tab">
          <div class="profile__details">
            <div class="profile__image">
              <i class="far fa-user"></i>
            </div>
  
            <div class="btn-container">
              <button class="primary-btn custom-btn">Upload New Image</button>
  
              <p>Remove</p>
            </div>
          </div>

          <div class="edit__profile__form">
            <form>

              <label>
                <b>Username</b>
                <input type="text" placeholder="Kadet">
              </label>

              <label>
                <b>Email</b>
                <input type="text" placeholder="techkadet@gmail.com">
              </label>

              <button class="primary-btn custom-btn">Save Changes</button>

            </form>
          </div>
        </article>
        
      </section>
    </div>

  </div>

</div>

{% endblock %}